ref_fasta_file:
  class: File
  path: /opt/MELTv2.1.5/reference/hs37d5.fa
transposon_zip_file: { class: File, path: /opt/MELTv2.1.5/me_refs/1KGP_Hg19/ALU_MELT.zip }
pre_geno_file: { class: File, path: /toil/ALU.pre_geno.tsv }
geno_files:
  - { class: File, path: /toil/NA12878.chr22.ALU.tsv }
