melt_config_file: { class: File, path: melt-split-step-2-grp.yml }
cwl_files:
 - { class: File, path: ../melt-grp.cwl }
input_files:
 - { class: File, path: ../NA12878.chr22.LINE1.aligned.final.sorted.bam }
 - { class: File, path: ../NA12878.chr22.LINE1.aligned.final.sorted.bam.bai }
 - { class: File, path: ../NA12878.chr22.LINE1.hum_breaks.sorted.bam }
 - { class: File, path: ../NA12878.chr22.LINE1.hum_breaks.sorted.bam.bai }
 - { class: File, path: ../NA12878.chr22.LINE1.pulled.sorted.bam }
 - { class: File, path: ../NA12878.chr22.LINE1.pulled.sorted.bam.bai }
 - { class: File, path: ../NA12878.chr22.LINE1.tmp.bed }
