melt_config_file: { class: File, path: melt-split-step-2-grp-alu.yml }
cwl_files:
 - { class: File, path: ../melt-grp.cwl }
input_files:
 - { class: File, path: ../NA12878.chr22.ALU.aligned.final.sorted.bam }
 - { class: File, path: ../NA12878.chr22.ALU.aligned.final.sorted.bam.bai }
 - { class: File, path: ../NA12878.chr22.ALU.hum_breaks.sorted.bam }
 - { class: File, path: ../NA12878.chr22.ALU.hum_breaks.sorted.bam.bai }
 - { class: File, path: ../NA12878.chr22.ALU.pulled.sorted.bam }
 - { class: File, path: ../NA12878.chr22.ALU.pulled.sorted.bam.bai }
 - { class: File, path: ../NA12878.chr22.ALU.tmp.bed }
