ref_fasta_file:
  class: File
  path: ../files/reference/hs37d5.fa
ref_bed_file:
  class: File
  path: ../files/1KGP_Hg19/hg19.genes.bed
transposon_zip_file: { class: File, path: ../files/me_refs/1KGP_Hg19/LINE1_MELT.zip }
aligned_bam_files:
  - { class: File, path: ../NA12878.chr22.LINE1.aligned.final.sorted.bam }
hum_breaks_bam_files:
  - { class: File, path: ../NA12878.chr22.LINE1.hum_breaks.sorted.bam }
pulled_bam_files:
  - { class: File, path: ../NA12878.chr22.LINE1.pulled.sorted.bam }
tmp_bed_files:
  - { class: File, path: ../NA12878.chr22.LINE1.tmp.bed }