reads_bam_uri: file://localhost/Users/jcrabtree/MELT/data/test-2/NA12878.chr22.sorted.bam
ref_fasta_file:
  class: File
  path: ../files/reference/hs37d5.fa
genes_bed_file: 
  class: File
  path: ../files/1KGP_Hg19/hg19.genes.bed
excluded_chromosomes: hs37d5/NC_007605
transposon_zip_files: 
  - { class: File, path: ../files/me_refs/1KGP_Hg19/LINE1_MELT.zip }
min_coverage: 8
