melt_config_file: { class: File, path: melt-split-step-4-vcf-alu.yml }
cwl_files:
 - { class: File, path: ../melt-vcf.cwl }
input_files:
 - { class: File, path: ../ALU.pre_geno.tsv }
 - { class: File, path: ../NA12878.chr22.ALU.tsv }
