#!/bin/bash

#export TOIL_DOCKER_NAME=toil
#export TOIL_DOCKER_REGISTRY=docker.io/umigs
#export TOIL_APPLIANCE_SELF=docker.io/umigs/toil-custom:1.0.0

#export RUNNER='toil-cwl-runner --retryCount 0'
export RUNNER='toil-cwl-runner --retryCount 0 --logLevel DEBUG'

# Mac OS X - specific workaround for Docker tasks
#export TMPDIR="/private${TMPDIR}"

# 2 samples, end-to-end:
#real54m13.339s
#user0m33.322s
#sys0m6.127s

# 10 samples, end-to-end:
#real294m16.598s
#user1m40.222s
#sys0m16.510s

# --------------------------------------------
# Test on AWS with mesos
# LINE1, ALU for 10 samples
# t2.medium (0.0464), i3.large (0.156) 
# combined cost = 0.2024/hour
# --------------------------------------------

#toil launch-cluster tcm1 --leaderNodeType t2.medium --zone us-east-1a --keyPairName kp1 --nodeTypes i3.large -w 1
#aws ecr get-login --region us-east-1 --no-include-email

# run docker login on leaderNode
# distribute /root/.docker/config.json to workers

#tar czvf test.tar.gz *.cwl *.yml run-10-samples.sh 10-samples-config.out
#toil rsync-cluster -z us-east-1a tcm1 test.tar.gz :/root/

# --------------------------------------------
# coverage - pre - ind
# --------------------------------------------

# 2 samples:
#real39m34.755s
#user0m15.877s
#sys0m2.850s

# step-1-pre.yml - config file minus the reads_bam_uri
# sample-uris.txt - list of URIs to feed to reads_bam_uri
# 10-samples-config.out/ - location for autogenerated config files
#
#./make-config-files.pl \
#  10-samples-config.in/step-1-pre.yml \
#  10-samples-config.in/step-2-grp.yml \
#  10-samples-config.in/step-3-gen.yml \
#  10-samples-config.in/step-4-vcf.yml \
#  10-samples-config.in/sample_uris.txt \
#  10-samples-config.out/

time $RUNNER \
  --jobStore aws:us-east-1:toil-tjs1 \
  --logFile melt-split-step-1.log \
  --batchSystem mesos \
melt-split-step-1.cwl 10-samples-config.out/step-1.yml

# --------------------------------------------
# group - LINE1, ALU etc.
# --------------------------------------------

#real4m59.087s
#user0m6.503s
#sys0m1.297s

time $RUNNER \
 --jobStore aws:us-east-1:toil-tjs1 \
 --logFile melt-split-step-2.log \
 --batchSystem mesos \
melt-split-step-2.cwl 10-samples-config.out/step-2.yml

# --------------------------------------------
# gen
# --------------------------------------------

# 2 samples
#real9m40.937s
#user0m7.121s
#sys0m1.312s

time $RUNNER \
 --jobStore aws:us-east-1:toil-tjs1 \
 --logFile melt-split-step-3.log \
 --batchSystem mesos \
melt-split-step-3.cwl 10-samples-config.out/step-3.yml

# --------------------------------------------
# vcf
# --------------------------------------------

# 2 samples:
#real0m35.841s
#user0m4.922s
#sys0m0.980s

time $RUNNER \
 --jobStore aws:us-east-1:toil-tjs1 \
 --logFile melt-split-step-4.log \
 --batchSystem mesos \
 melt-split-step-4.cwl 10-samples-config.out/step-4.yml



